# .goreleaser.yml
version: 2
project_name: SuperSubtitles

# Configures the release process on GitHub
# https://goreleaser.com/customization/release/
release:
  github:
    owner: Belphemur
    name: SuperSubtitles
  include_meta: true

# Configures the changelog generation
# https://goreleaser.com/customization/changelog/
changelog:
  sort: asc
  use: github
  format: "{{.SHA}}: {{.Message}} (@{{.AuthorUsername}})"
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "Performance"
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2

# Hooks to run before the build process starts
# https://goreleaser.com/customization/hooks/
before:
  hooks:
    - go mod tidy

# Configures the Go build process
# https://goreleaser.com/customization/build/
builds:
  - id: super-subtitles
    main: ./cmd/proxy
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    # ensures mod timestamp to be the commit timestamp
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      # trims path
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{ .CommitDate }}
    env:
      - CGO_ENABLED=0

# Configures the binary archive generation
# https://goreleaser.com/customization/archive/
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}

# Configures the checksum file generation
# https://goreleaser.com/customization/checksum/
checksum:
  name_template: "checksums.txt"

# Creates a source code archive (tar.gz and zip)
# https://goreleaser.com/customization/source/
source:
  enabled: true

# Configures Go Modules settings
# https://goreleaser.com/customization/gomod/
gomod:
  proxy: true

# Change the digests filename for attestation
# https://goreleaser.com/customization/docker_digest/
docker_digest:
  name_template: "digests.txt"

# Creates SBOMs (Software Bill of Materials)
# https://goreleaser.com/customization/sbom/
sboms:
  - id: archive
    artifacts: archive
  - id: source
    artifacts: source

# Creates Docker images and pushes them to registries using Docker v2 API
# https://goreleaser.com/customization/docker/
dockers_v2:
  - id: super-subtitles-image
    ids:
      - super-subtitles
    dockerfile: build/Dockerfile
    platforms:
      - linux/amd64
      - linux/arm64
    images:
      - "ghcr.io/belphemur/supersubtitles"
    tags:
      - "{{ .Version }}"
      - latest
    extra_files:
      - config/config.yaml
    annotations:
      "org.opencontainers.image.description": "A Go proxy service that scrapes and normalizes subtitle data from feliratok.eu."
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"
    labels:
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"
      "org.opencontainers.image.description": "A Go proxy service that scrapes and normalizes subtitle data from feliratok.eu."
