// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.1
// source: api/proto/v1/supersubtitles.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SuperSubtitlesService_GetShowList_FullMethodName        = "/supersubtitles.v1.SuperSubtitlesService/GetShowList"
	SuperSubtitlesService_GetSubtitles_FullMethodName       = "/supersubtitles.v1.SuperSubtitlesService/GetSubtitles"
	SuperSubtitlesService_GetShowSubtitles_FullMethodName   = "/supersubtitles.v1.SuperSubtitlesService/GetShowSubtitles"
	SuperSubtitlesService_CheckForUpdates_FullMethodName    = "/supersubtitles.v1.SuperSubtitlesService/CheckForUpdates"
	SuperSubtitlesService_DownloadSubtitle_FullMethodName   = "/supersubtitles.v1.SuperSubtitlesService/DownloadSubtitle"
	SuperSubtitlesService_GetRecentSubtitles_FullMethodName = "/supersubtitles.v1.SuperSubtitlesService/GetRecentSubtitles"
)

// SuperSubtitlesServiceClient is the client API for SuperSubtitlesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SuperSubtitlesService provides access to TV show and subtitle information
type SuperSubtitlesServiceClient interface {
	// GetShowList retrieves all available TV shows
	GetShowList(ctx context.Context, in *GetShowListRequest, opts ...grpc.CallOption) (*GetShowListResponse, error)
	// GetSubtitles retrieves all subtitles for a specific show
	GetSubtitles(ctx context.Context, in *GetSubtitlesRequest, opts ...grpc.CallOption) (*GetSubtitlesResponse, error)
	// GetShowSubtitles retrieves shows with their subtitles and third-party IDs
	GetShowSubtitles(ctx context.Context, in *GetShowSubtitlesRequest, opts ...grpc.CallOption) (*GetShowSubtitlesResponse, error)
	// CheckForUpdates checks if there are new subtitles available since a given content ID
	CheckForUpdates(ctx context.Context, in *CheckForUpdatesRequest, opts ...grpc.CallOption) (*CheckForUpdatesResponse, error)
	// DownloadSubtitle downloads a specific subtitle file
	DownloadSubtitle(ctx context.Context, in *DownloadSubtitleRequest, opts ...grpc.CallOption) (*DownloadSubtitleResponse, error)
	// GetRecentSubtitles retrieves recently uploaded subtitles
	GetRecentSubtitles(ctx context.Context, in *GetRecentSubtitlesRequest, opts ...grpc.CallOption) (*GetRecentSubtitlesResponse, error)
}

type superSubtitlesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSuperSubtitlesServiceClient(cc grpc.ClientConnInterface) SuperSubtitlesServiceClient {
	return &superSubtitlesServiceClient{cc}
}

func (c *superSubtitlesServiceClient) GetShowList(ctx context.Context, in *GetShowListRequest, opts ...grpc.CallOption) (*GetShowListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetShowListResponse)
	err := c.cc.Invoke(ctx, SuperSubtitlesService_GetShowList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *superSubtitlesServiceClient) GetSubtitles(ctx context.Context, in *GetSubtitlesRequest, opts ...grpc.CallOption) (*GetSubtitlesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSubtitlesResponse)
	err := c.cc.Invoke(ctx, SuperSubtitlesService_GetSubtitles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *superSubtitlesServiceClient) GetShowSubtitles(ctx context.Context, in *GetShowSubtitlesRequest, opts ...grpc.CallOption) (*GetShowSubtitlesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetShowSubtitlesResponse)
	err := c.cc.Invoke(ctx, SuperSubtitlesService_GetShowSubtitles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *superSubtitlesServiceClient) CheckForUpdates(ctx context.Context, in *CheckForUpdatesRequest, opts ...grpc.CallOption) (*CheckForUpdatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckForUpdatesResponse)
	err := c.cc.Invoke(ctx, SuperSubtitlesService_CheckForUpdates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *superSubtitlesServiceClient) DownloadSubtitle(ctx context.Context, in *DownloadSubtitleRequest, opts ...grpc.CallOption) (*DownloadSubtitleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DownloadSubtitleResponse)
	err := c.cc.Invoke(ctx, SuperSubtitlesService_DownloadSubtitle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *superSubtitlesServiceClient) GetRecentSubtitles(ctx context.Context, in *GetRecentSubtitlesRequest, opts ...grpc.CallOption) (*GetRecentSubtitlesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRecentSubtitlesResponse)
	err := c.cc.Invoke(ctx, SuperSubtitlesService_GetRecentSubtitles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SuperSubtitlesServiceServer is the server API for SuperSubtitlesService service.
// All implementations must embed UnimplementedSuperSubtitlesServiceServer
// for forward compatibility.
//
// SuperSubtitlesService provides access to TV show and subtitle information
type SuperSubtitlesServiceServer interface {
	// GetShowList retrieves all available TV shows
	GetShowList(context.Context, *GetShowListRequest) (*GetShowListResponse, error)
	// GetSubtitles retrieves all subtitles for a specific show
	GetSubtitles(context.Context, *GetSubtitlesRequest) (*GetSubtitlesResponse, error)
	// GetShowSubtitles retrieves shows with their subtitles and third-party IDs
	GetShowSubtitles(context.Context, *GetShowSubtitlesRequest) (*GetShowSubtitlesResponse, error)
	// CheckForUpdates checks if there are new subtitles available since a given content ID
	CheckForUpdates(context.Context, *CheckForUpdatesRequest) (*CheckForUpdatesResponse, error)
	// DownloadSubtitle downloads a specific subtitle file
	DownloadSubtitle(context.Context, *DownloadSubtitleRequest) (*DownloadSubtitleResponse, error)
	// GetRecentSubtitles retrieves recently uploaded subtitles
	GetRecentSubtitles(context.Context, *GetRecentSubtitlesRequest) (*GetRecentSubtitlesResponse, error)
	mustEmbedUnimplementedSuperSubtitlesServiceServer()
}

// UnimplementedSuperSubtitlesServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSuperSubtitlesServiceServer struct{}

func (UnimplementedSuperSubtitlesServiceServer) GetShowList(context.Context, *GetShowListRequest) (*GetShowListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetShowList not implemented")
}
func (UnimplementedSuperSubtitlesServiceServer) GetSubtitles(context.Context, *GetSubtitlesRequest) (*GetSubtitlesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSubtitles not implemented")
}
func (UnimplementedSuperSubtitlesServiceServer) GetShowSubtitles(context.Context, *GetShowSubtitlesRequest) (*GetShowSubtitlesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetShowSubtitles not implemented")
}
func (UnimplementedSuperSubtitlesServiceServer) CheckForUpdates(context.Context, *CheckForUpdatesRequest) (*CheckForUpdatesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckForUpdates not implemented")
}
func (UnimplementedSuperSubtitlesServiceServer) DownloadSubtitle(context.Context, *DownloadSubtitleRequest) (*DownloadSubtitleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DownloadSubtitle not implemented")
}
func (UnimplementedSuperSubtitlesServiceServer) GetRecentSubtitles(context.Context, *GetRecentSubtitlesRequest) (*GetRecentSubtitlesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRecentSubtitles not implemented")
}
func (UnimplementedSuperSubtitlesServiceServer) mustEmbedUnimplementedSuperSubtitlesServiceServer() {}
func (UnimplementedSuperSubtitlesServiceServer) testEmbeddedByValue()                               {}

// UnsafeSuperSubtitlesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SuperSubtitlesServiceServer will
// result in compilation errors.
type UnsafeSuperSubtitlesServiceServer interface {
	mustEmbedUnimplementedSuperSubtitlesServiceServer()
}

func RegisterSuperSubtitlesServiceServer(s grpc.ServiceRegistrar, srv SuperSubtitlesServiceServer) {
	// If the following call panics, it indicates UnimplementedSuperSubtitlesServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SuperSubtitlesService_ServiceDesc, srv)
}

func _SuperSubtitlesService_GetShowList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShowListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SuperSubtitlesServiceServer).GetShowList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SuperSubtitlesService_GetShowList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SuperSubtitlesServiceServer).GetShowList(ctx, req.(*GetShowListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SuperSubtitlesService_GetSubtitles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSubtitlesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SuperSubtitlesServiceServer).GetSubtitles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SuperSubtitlesService_GetSubtitles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SuperSubtitlesServiceServer).GetSubtitles(ctx, req.(*GetSubtitlesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SuperSubtitlesService_GetShowSubtitles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShowSubtitlesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SuperSubtitlesServiceServer).GetShowSubtitles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SuperSubtitlesService_GetShowSubtitles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SuperSubtitlesServiceServer).GetShowSubtitles(ctx, req.(*GetShowSubtitlesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SuperSubtitlesService_CheckForUpdates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckForUpdatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SuperSubtitlesServiceServer).CheckForUpdates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SuperSubtitlesService_CheckForUpdates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SuperSubtitlesServiceServer).CheckForUpdates(ctx, req.(*CheckForUpdatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SuperSubtitlesService_DownloadSubtitle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadSubtitleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SuperSubtitlesServiceServer).DownloadSubtitle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SuperSubtitlesService_DownloadSubtitle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SuperSubtitlesServiceServer).DownloadSubtitle(ctx, req.(*DownloadSubtitleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SuperSubtitlesService_GetRecentSubtitles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecentSubtitlesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SuperSubtitlesServiceServer).GetRecentSubtitles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SuperSubtitlesService_GetRecentSubtitles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SuperSubtitlesServiceServer).GetRecentSubtitles(ctx, req.(*GetRecentSubtitlesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SuperSubtitlesService_ServiceDesc is the grpc.ServiceDesc for SuperSubtitlesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SuperSubtitlesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "supersubtitles.v1.SuperSubtitlesService",
	HandlerType: (*SuperSubtitlesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetShowList",
			Handler:    _SuperSubtitlesService_GetShowList_Handler,
		},
		{
			MethodName: "GetSubtitles",
			Handler:    _SuperSubtitlesService_GetSubtitles_Handler,
		},
		{
			MethodName: "GetShowSubtitles",
			Handler:    _SuperSubtitlesService_GetShowSubtitles_Handler,
		},
		{
			MethodName: "CheckForUpdates",
			Handler:    _SuperSubtitlesService_CheckForUpdates_Handler,
		},
		{
			MethodName: "DownloadSubtitle",
			Handler:    _SuperSubtitlesService_DownloadSubtitle_Handler,
		},
		{
			MethodName: "GetRecentSubtitles",
			Handler:    _SuperSubtitlesService_GetRecentSubtitles_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/v1/supersubtitles.proto",
}
