// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: supersubtitles.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SuperSubtitlesService_GetShowList_FullMethodName        = "/supersubtitles.v1.SuperSubtitlesService/GetShowList"
	SuperSubtitlesService_GetSubtitles_FullMethodName       = "/supersubtitles.v1.SuperSubtitlesService/GetSubtitles"
	SuperSubtitlesService_GetShowSubtitles_FullMethodName   = "/supersubtitles.v1.SuperSubtitlesService/GetShowSubtitles"
	SuperSubtitlesService_CheckForUpdates_FullMethodName    = "/supersubtitles.v1.SuperSubtitlesService/CheckForUpdates"
	SuperSubtitlesService_DownloadSubtitle_FullMethodName   = "/supersubtitles.v1.SuperSubtitlesService/DownloadSubtitle"
	SuperSubtitlesService_GetRecentSubtitles_FullMethodName = "/supersubtitles.v1.SuperSubtitlesService/GetRecentSubtitles"
)

// SuperSubtitlesServiceClient is the client API for SuperSubtitlesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SuperSubtitlesService provides access to TV show and subtitle information
// Uses server-side streaming for list/collection endpoints to improve
// time-to-first-result and reduce memory usage.
type SuperSubtitlesServiceClient interface {
	// GetShowList streams all available TV shows
	GetShowList(ctx context.Context, in *GetShowListRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Show], error)
	// GetSubtitles streams all subtitles for a specific show
	GetSubtitles(ctx context.Context, in *GetSubtitlesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Subtitle], error)
	// GetShowSubtitles streams show information and subtitles for multiple shows.
	// Streams ShowSubtitleItem messages which contain either show info (show + third-party IDs)
	// or a subtitle, linked together by show_id.
	GetShowSubtitles(ctx context.Context, in *GetShowSubtitlesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ShowSubtitleItem], error)
	// CheckForUpdates checks if there are new subtitles available since a given content ID
	CheckForUpdates(ctx context.Context, in *CheckForUpdatesRequest, opts ...grpc.CallOption) (*CheckForUpdatesResponse, error)
	// DownloadSubtitle downloads a specific subtitle file
	DownloadSubtitle(ctx context.Context, in *DownloadSubtitleRequest, opts ...grpc.CallOption) (*DownloadSubtitleResponse, error)
	// GetRecentSubtitles streams recently uploaded subtitles grouped by show.
	// Streams ShowSubtitleItem messages which contain either show info or a subtitle.
	GetRecentSubtitles(ctx context.Context, in *GetRecentSubtitlesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ShowSubtitleItem], error)
}

type superSubtitlesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSuperSubtitlesServiceClient(cc grpc.ClientConnInterface) SuperSubtitlesServiceClient {
	return &superSubtitlesServiceClient{cc}
}

func (c *superSubtitlesServiceClient) GetShowList(ctx context.Context, in *GetShowListRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Show], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SuperSubtitlesService_ServiceDesc.Streams[0], SuperSubtitlesService_GetShowList_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetShowListRequest, Show]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SuperSubtitlesService_GetShowListClient = grpc.ServerStreamingClient[Show]

func (c *superSubtitlesServiceClient) GetSubtitles(ctx context.Context, in *GetSubtitlesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Subtitle], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SuperSubtitlesService_ServiceDesc.Streams[1], SuperSubtitlesService_GetSubtitles_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetSubtitlesRequest, Subtitle]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SuperSubtitlesService_GetSubtitlesClient = grpc.ServerStreamingClient[Subtitle]

func (c *superSubtitlesServiceClient) GetShowSubtitles(ctx context.Context, in *GetShowSubtitlesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ShowSubtitleItem], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SuperSubtitlesService_ServiceDesc.Streams[2], SuperSubtitlesService_GetShowSubtitles_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetShowSubtitlesRequest, ShowSubtitleItem]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SuperSubtitlesService_GetShowSubtitlesClient = grpc.ServerStreamingClient[ShowSubtitleItem]

func (c *superSubtitlesServiceClient) CheckForUpdates(ctx context.Context, in *CheckForUpdatesRequest, opts ...grpc.CallOption) (*CheckForUpdatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckForUpdatesResponse)
	err := c.cc.Invoke(ctx, SuperSubtitlesService_CheckForUpdates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *superSubtitlesServiceClient) DownloadSubtitle(ctx context.Context, in *DownloadSubtitleRequest, opts ...grpc.CallOption) (*DownloadSubtitleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DownloadSubtitleResponse)
	err := c.cc.Invoke(ctx, SuperSubtitlesService_DownloadSubtitle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *superSubtitlesServiceClient) GetRecentSubtitles(ctx context.Context, in *GetRecentSubtitlesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ShowSubtitleItem], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SuperSubtitlesService_ServiceDesc.Streams[3], SuperSubtitlesService_GetRecentSubtitles_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetRecentSubtitlesRequest, ShowSubtitleItem]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SuperSubtitlesService_GetRecentSubtitlesClient = grpc.ServerStreamingClient[ShowSubtitleItem]

// SuperSubtitlesServiceServer is the server API for SuperSubtitlesService service.
// All implementations must embed UnimplementedSuperSubtitlesServiceServer
// for forward compatibility.
//
// SuperSubtitlesService provides access to TV show and subtitle information
// Uses server-side streaming for list/collection endpoints to improve
// time-to-first-result and reduce memory usage.
type SuperSubtitlesServiceServer interface {
	// GetShowList streams all available TV shows
	GetShowList(*GetShowListRequest, grpc.ServerStreamingServer[Show]) error
	// GetSubtitles streams all subtitles for a specific show
	GetSubtitles(*GetSubtitlesRequest, grpc.ServerStreamingServer[Subtitle]) error
	// GetShowSubtitles streams show information and subtitles for multiple shows.
	// Streams ShowSubtitleItem messages which contain either show info (show + third-party IDs)
	// or a subtitle, linked together by show_id.
	GetShowSubtitles(*GetShowSubtitlesRequest, grpc.ServerStreamingServer[ShowSubtitleItem]) error
	// CheckForUpdates checks if there are new subtitles available since a given content ID
	CheckForUpdates(context.Context, *CheckForUpdatesRequest) (*CheckForUpdatesResponse, error)
	// DownloadSubtitle downloads a specific subtitle file
	DownloadSubtitle(context.Context, *DownloadSubtitleRequest) (*DownloadSubtitleResponse, error)
	// GetRecentSubtitles streams recently uploaded subtitles grouped by show.
	// Streams ShowSubtitleItem messages which contain either show info or a subtitle.
	GetRecentSubtitles(*GetRecentSubtitlesRequest, grpc.ServerStreamingServer[ShowSubtitleItem]) error
	mustEmbedUnimplementedSuperSubtitlesServiceServer()
}

// UnimplementedSuperSubtitlesServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSuperSubtitlesServiceServer struct{}

func (UnimplementedSuperSubtitlesServiceServer) GetShowList(*GetShowListRequest, grpc.ServerStreamingServer[Show]) error {
	return status.Error(codes.Unimplemented, "method GetShowList not implemented")
}
func (UnimplementedSuperSubtitlesServiceServer) GetSubtitles(*GetSubtitlesRequest, grpc.ServerStreamingServer[Subtitle]) error {
	return status.Error(codes.Unimplemented, "method GetSubtitles not implemented")
}
func (UnimplementedSuperSubtitlesServiceServer) GetShowSubtitles(*GetShowSubtitlesRequest, grpc.ServerStreamingServer[ShowSubtitleItem]) error {
	return status.Error(codes.Unimplemented, "method GetShowSubtitles not implemented")
}
func (UnimplementedSuperSubtitlesServiceServer) CheckForUpdates(context.Context, *CheckForUpdatesRequest) (*CheckForUpdatesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckForUpdates not implemented")
}
func (UnimplementedSuperSubtitlesServiceServer) DownloadSubtitle(context.Context, *DownloadSubtitleRequest) (*DownloadSubtitleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DownloadSubtitle not implemented")
}
func (UnimplementedSuperSubtitlesServiceServer) GetRecentSubtitles(*GetRecentSubtitlesRequest, grpc.ServerStreamingServer[ShowSubtitleItem]) error {
	return status.Error(codes.Unimplemented, "method GetRecentSubtitles not implemented")
}
func (UnimplementedSuperSubtitlesServiceServer) mustEmbedUnimplementedSuperSubtitlesServiceServer() {}
func (UnimplementedSuperSubtitlesServiceServer) testEmbeddedByValue()                               {}

// UnsafeSuperSubtitlesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SuperSubtitlesServiceServer will
// result in compilation errors.
type UnsafeSuperSubtitlesServiceServer interface {
	mustEmbedUnimplementedSuperSubtitlesServiceServer()
}

func RegisterSuperSubtitlesServiceServer(s grpc.ServiceRegistrar, srv SuperSubtitlesServiceServer) {
	// If the following call panics, it indicates UnimplementedSuperSubtitlesServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SuperSubtitlesService_ServiceDesc, srv)
}

func _SuperSubtitlesService_GetShowList_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetShowListRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SuperSubtitlesServiceServer).GetShowList(m, &grpc.GenericServerStream[GetShowListRequest, Show]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SuperSubtitlesService_GetShowListServer = grpc.ServerStreamingServer[Show]

func _SuperSubtitlesService_GetSubtitles_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetSubtitlesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SuperSubtitlesServiceServer).GetSubtitles(m, &grpc.GenericServerStream[GetSubtitlesRequest, Subtitle]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SuperSubtitlesService_GetSubtitlesServer = grpc.ServerStreamingServer[Subtitle]

func _SuperSubtitlesService_GetShowSubtitles_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetShowSubtitlesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SuperSubtitlesServiceServer).GetShowSubtitles(m, &grpc.GenericServerStream[GetShowSubtitlesRequest, ShowSubtitleItem]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SuperSubtitlesService_GetShowSubtitlesServer = grpc.ServerStreamingServer[ShowSubtitleItem]

func _SuperSubtitlesService_CheckForUpdates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckForUpdatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SuperSubtitlesServiceServer).CheckForUpdates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SuperSubtitlesService_CheckForUpdates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SuperSubtitlesServiceServer).CheckForUpdates(ctx, req.(*CheckForUpdatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SuperSubtitlesService_DownloadSubtitle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadSubtitleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SuperSubtitlesServiceServer).DownloadSubtitle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SuperSubtitlesService_DownloadSubtitle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SuperSubtitlesServiceServer).DownloadSubtitle(ctx, req.(*DownloadSubtitleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SuperSubtitlesService_GetRecentSubtitles_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetRecentSubtitlesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SuperSubtitlesServiceServer).GetRecentSubtitles(m, &grpc.GenericServerStream[GetRecentSubtitlesRequest, ShowSubtitleItem]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SuperSubtitlesService_GetRecentSubtitlesServer = grpc.ServerStreamingServer[ShowSubtitleItem]

// SuperSubtitlesService_ServiceDesc is the grpc.ServiceDesc for SuperSubtitlesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SuperSubtitlesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "supersubtitles.v1.SuperSubtitlesService",
	HandlerType: (*SuperSubtitlesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckForUpdates",
			Handler:    _SuperSubtitlesService_CheckForUpdates_Handler,
		},
		{
			MethodName: "DownloadSubtitle",
			Handler:    _SuperSubtitlesService_DownloadSubtitle_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetShowList",
			Handler:       _SuperSubtitlesService_GetShowList_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetSubtitles",
			Handler:       _SuperSubtitlesService_GetSubtitles_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetShowSubtitles",
			Handler:       _SuperSubtitlesService_GetShowSubtitles_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetRecentSubtitles",
			Handler:       _SuperSubtitlesService_GetRecentSubtitles_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "supersubtitles.proto",
}
