// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: supersubtitles.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Quality represents the video quality of a subtitle
type Quality int32

const (
	Quality_QUALITY_UNSPECIFIED Quality = 0
	Quality_QUALITY_360P        Quality = 1
	Quality_QUALITY_480P        Quality = 2
	Quality_QUALITY_720P        Quality = 3
	Quality_QUALITY_1080P       Quality = 4
	Quality_QUALITY_2160P       Quality = 5 // 4K
)

// Enum value maps for Quality.
var (
	Quality_name = map[int32]string{
		0: "QUALITY_UNSPECIFIED",
		1: "QUALITY_360P",
		2: "QUALITY_480P",
		3: "QUALITY_720P",
		4: "QUALITY_1080P",
		5: "QUALITY_2160P",
	}
	Quality_value = map[string]int32{
		"QUALITY_UNSPECIFIED": 0,
		"QUALITY_360P":        1,
		"QUALITY_480P":        2,
		"QUALITY_720P":        3,
		"QUALITY_1080P":       4,
		"QUALITY_2160P":       5,
	}
)

func (x Quality) Enum() *Quality {
	p := new(Quality)
	*p = x
	return p
}

func (x Quality) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Quality) Descriptor() protoreflect.EnumDescriptor {
	return file_supersubtitles_proto_enumTypes[0].Descriptor()
}

func (Quality) Type() protoreflect.EnumType {
	return &file_supersubtitles_proto_enumTypes[0]
}

func (x Quality) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Quality.Descriptor instead.
func (Quality) EnumDescriptor() ([]byte, []int) {
	return file_supersubtitles_proto_rawDescGZIP(), []int{0}
}

// Show represents a TV show with basic information
type Show struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id            int64                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Year          int32                  `protobuf:"varint,3,opt,name=year,proto3" json:"year,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,4,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Show) Reset() {
	*x = Show{}
	mi := &file_supersubtitles_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Show) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Show) ProtoMessage() {}

func (x *Show) ProtoReflect() protoreflect.Message {
	mi := &file_supersubtitles_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Show.ProtoReflect.Descriptor instead.
func (*Show) Descriptor() ([]byte, []int) {
	return file_supersubtitles_proto_rawDescGZIP(), []int{0}
}

func (x *Show) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Show) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Show) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *Show) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

// ThirdPartyIds represents identifiers from various third-party services
type ThirdPartyIds struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImdbId        string                 `protobuf:"bytes,1,opt,name=imdb_id,json=imdbId,proto3" json:"imdb_id,omitempty"`          // IMDB identifier
	TvdbId        int64                  `protobuf:"varint,2,opt,name=tvdb_id,json=tvdbId,proto3" json:"tvdb_id,omitempty"`         // TVDB identifier
	TvMazeId      int64                  `protobuf:"varint,3,opt,name=tv_maze_id,json=tvMazeId,proto3" json:"tv_maze_id,omitempty"` // TVMaze identifier
	TraktId       int64                  `protobuf:"varint,4,opt,name=trakt_id,json=traktId,proto3" json:"trakt_id,omitempty"`      // Trakt identifier
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThirdPartyIds) Reset() {
	*x = ThirdPartyIds{}
	mi := &file_supersubtitles_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThirdPartyIds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThirdPartyIds) ProtoMessage() {}

func (x *ThirdPartyIds) ProtoReflect() protoreflect.Message {
	mi := &file_supersubtitles_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThirdPartyIds.ProtoReflect.Descriptor instead.
func (*ThirdPartyIds) Descriptor() ([]byte, []int) {
	return file_supersubtitles_proto_rawDescGZIP(), []int{1}
}

func (x *ThirdPartyIds) GetImdbId() string {
	if x != nil {
		return x.ImdbId
	}
	return ""
}

func (x *ThirdPartyIds) GetTvdbId() int64 {
	if x != nil {
		return x.TvdbId
	}
	return 0
}

func (x *ThirdPartyIds) GetTvMazeId() int64 {
	if x != nil {
		return x.TvMazeId
	}
	return 0
}

func (x *ThirdPartyIds) GetTraktId() int64 {
	if x != nil {
		return x.TraktId
	}
	return 0
}

// Subtitle represents a normalized subtitle
type Subtitle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ShowId        int64                  `protobuf:"varint,2,opt,name=show_id,json=showId,proto3" json:"show_id,omitempty"`
	ShowName      string                 `protobuf:"bytes,3,opt,name=show_name,json=showName,proto3" json:"show_name,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Language      string                 `protobuf:"bytes,5,opt,name=language,proto3" json:"language,omitempty"`
	Season        int32                  `protobuf:"varint,6,opt,name=season,proto3" json:"season,omitempty"`
	Episode       int32                  `protobuf:"varint,7,opt,name=episode,proto3" json:"episode,omitempty"`
	Filename      string                 `protobuf:"bytes,8,opt,name=filename,proto3" json:"filename,omitempty"`
	DownloadUrl   string                 `protobuf:"bytes,9,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"`
	Uploader      string                 `protobuf:"bytes,10,opt,name=uploader,proto3" json:"uploader,omitempty"`
	UploadedAt    *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=uploaded_at,json=uploadedAt,proto3" json:"uploaded_at,omitempty"`
	Qualities     []Quality              `protobuf:"varint,12,rep,packed,name=qualities,proto3,enum=supersubtitles.v1.Quality" json:"qualities,omitempty"`
	ReleaseGroups []string               `protobuf:"bytes,13,rep,name=release_groups,json=releaseGroups,proto3" json:"release_groups,omitempty"`
	Release       string                 `protobuf:"bytes,14,opt,name=release,proto3" json:"release,omitempty"`
	IsSeasonPack  bool                   `protobuf:"varint,15,opt,name=is_season_pack,json=isSeasonPack,proto3" json:"is_season_pack,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subtitle) Reset() {
	*x = Subtitle{}
	mi := &file_supersubtitles_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subtitle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subtitle) ProtoMessage() {}

func (x *Subtitle) ProtoReflect() protoreflect.Message {
	mi := &file_supersubtitles_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subtitle.ProtoReflect.Descriptor instead.
func (*Subtitle) Descriptor() ([]byte, []int) {
	return file_supersubtitles_proto_rawDescGZIP(), []int{2}
}

func (x *Subtitle) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Subtitle) GetShowId() int64 {
	if x != nil {
		return x.ShowId
	}
	return 0
}

func (x *Subtitle) GetShowName() string {
	if x != nil {
		return x.ShowName
	}
	return ""
}

func (x *Subtitle) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Subtitle) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *Subtitle) GetSeason() int32 {
	if x != nil {
		return x.Season
	}
	return 0
}

func (x *Subtitle) GetEpisode() int32 {
	if x != nil {
		return x.Episode
	}
	return 0
}

func (x *Subtitle) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *Subtitle) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

func (x *Subtitle) GetUploader() string {
	if x != nil {
		return x.Uploader
	}
	return ""
}

func (x *Subtitle) GetUploadedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UploadedAt
	}
	return nil
}

func (x *Subtitle) GetQualities() []Quality {
	if x != nil {
		return x.Qualities
	}
	return nil
}

func (x *Subtitle) GetReleaseGroups() []string {
	if x != nil {
		return x.ReleaseGroups
	}
	return nil
}

func (x *Subtitle) GetRelease() string {
	if x != nil {
		return x.Release
	}
	return ""
}

func (x *Subtitle) GetIsSeasonPack() bool {
	if x != nil {
		return x.IsSeasonPack
	}
	return false
}

// ShowInfo represents a TV show with its third-party IDs (sent once per show in a stream)
type ShowInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Show          *Show                  `protobuf:"bytes,1,opt,name=show,proto3" json:"show,omitempty"`
	ThirdPartyIds *ThirdPartyIds         `protobuf:"bytes,2,opt,name=third_party_ids,json=thirdPartyIds,proto3" json:"third_party_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowInfo) Reset() {
	*x = ShowInfo{}
	mi := &file_supersubtitles_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowInfo) ProtoMessage() {}

func (x *ShowInfo) ProtoReflect() protoreflect.Message {
	mi := &file_supersubtitles_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowInfo.ProtoReflect.Descriptor instead.
func (*ShowInfo) Descriptor() ([]byte, []int) {
	return file_supersubtitles_proto_rawDescGZIP(), []int{3}
}

func (x *ShowInfo) GetShow() *Show {
	if x != nil {
		return x.Show
	}
	return nil
}

func (x *ShowInfo) GetThirdPartyIds() *ThirdPartyIds {
	if x != nil {
		return x.ThirdPartyIds
	}
	return nil
}

// ShowSubtitleItem is a streaming message for GetShowSubtitles/GetRecentSubtitles.
// Each item is either show information or a subtitle, linked by show_id.
type ShowSubtitleItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Item:
	//
	//	*ShowSubtitleItem_ShowInfo
	//	*ShowSubtitleItem_Subtitle
	Item          isShowSubtitleItem_Item `protobuf_oneof:"item"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowSubtitleItem) Reset() {
	*x = ShowSubtitleItem{}
	mi := &file_supersubtitles_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowSubtitleItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowSubtitleItem) ProtoMessage() {}

func (x *ShowSubtitleItem) ProtoReflect() protoreflect.Message {
	mi := &file_supersubtitles_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowSubtitleItem.ProtoReflect.Descriptor instead.
func (*ShowSubtitleItem) Descriptor() ([]byte, []int) {
	return file_supersubtitles_proto_rawDescGZIP(), []int{4}
}

func (x *ShowSubtitleItem) GetItem() isShowSubtitleItem_Item {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *ShowSubtitleItem) GetShowInfo() *ShowInfo {
	if x != nil {
		if x, ok := x.Item.(*ShowSubtitleItem_ShowInfo); ok {
			return x.ShowInfo
		}
	}
	return nil
}

func (x *ShowSubtitleItem) GetSubtitle() *Subtitle {
	if x != nil {
		if x, ok := x.Item.(*ShowSubtitleItem_Subtitle); ok {
			return x.Subtitle
		}
	}
	return nil
}

type isShowSubtitleItem_Item interface {
	isShowSubtitleItem_Item()
}

type ShowSubtitleItem_ShowInfo struct {
	ShowInfo *ShowInfo `protobuf:"bytes,1,opt,name=show_info,json=showInfo,proto3,oneof"` // Show metadata with third-party IDs
}

type ShowSubtitleItem_Subtitle struct {
	Subtitle *Subtitle `protobuf:"bytes,2,opt,name=subtitle,proto3,oneof"` // A single subtitle belonging to a show (use show_id to link)
}

func (*ShowSubtitleItem_ShowInfo) isShowSubtitleItem_Item() {}

func (*ShowSubtitleItem_Subtitle) isShowSubtitleItem_Item() {}

// GetShowListRequest requests the list of all available shows
type GetShowListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShowListRequest) Reset() {
	*x = GetShowListRequest{}
	mi := &file_supersubtitles_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShowListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShowListRequest) ProtoMessage() {}

func (x *GetShowListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_supersubtitles_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShowListRequest.ProtoReflect.Descriptor instead.
func (*GetShowListRequest) Descriptor() ([]byte, []int) {
	return file_supersubtitles_proto_rawDescGZIP(), []int{5}
}

// GetSubtitlesRequest requests subtitles for a specific show
type GetSubtitlesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShowId        int64                  `protobuf:"varint,1,opt,name=show_id,json=showId,proto3" json:"show_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubtitlesRequest) Reset() {
	*x = GetSubtitlesRequest{}
	mi := &file_supersubtitles_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubtitlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubtitlesRequest) ProtoMessage() {}

func (x *GetSubtitlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_supersubtitles_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubtitlesRequest.ProtoReflect.Descriptor instead.
func (*GetSubtitlesRequest) Descriptor() ([]byte, []int) {
	return file_supersubtitles_proto_rawDescGZIP(), []int{6}
}

func (x *GetSubtitlesRequest) GetShowId() int64 {
	if x != nil {
		return x.ShowId
	}
	return 0
}

// GetShowSubtitlesRequest requests shows with their subtitles and third-party IDs
type GetShowSubtitlesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shows         []*Show                `protobuf:"bytes,1,rep,name=shows,proto3" json:"shows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShowSubtitlesRequest) Reset() {
	*x = GetShowSubtitlesRequest{}
	mi := &file_supersubtitles_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShowSubtitlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShowSubtitlesRequest) ProtoMessage() {}

func (x *GetShowSubtitlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_supersubtitles_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShowSubtitlesRequest.ProtoReflect.Descriptor instead.
func (*GetShowSubtitlesRequest) Descriptor() ([]byte, []int) {
	return file_supersubtitles_proto_rawDescGZIP(), []int{7}
}

func (x *GetShowSubtitlesRequest) GetShows() []*Show {
	if x != nil {
		return x.Shows
	}
	return nil
}

// CheckForUpdatesRequest checks for new content since a given content ID
type CheckForUpdatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentId     string                 `protobuf:"bytes,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckForUpdatesRequest) Reset() {
	*x = CheckForUpdatesRequest{}
	mi := &file_supersubtitles_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckForUpdatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckForUpdatesRequest) ProtoMessage() {}

func (x *CheckForUpdatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_supersubtitles_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckForUpdatesRequest.ProtoReflect.Descriptor instead.
func (*CheckForUpdatesRequest) Descriptor() ([]byte, []int) {
	return file_supersubtitles_proto_rawDescGZIP(), []int{8}
}

func (x *CheckForUpdatesRequest) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

// CheckForUpdatesResponse contains update availability information
type CheckForUpdatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilmCount     int32                  `protobuf:"varint,1,opt,name=film_count,json=filmCount,proto3" json:"film_count,omitempty"`
	SeriesCount   int32                  `protobuf:"varint,2,opt,name=series_count,json=seriesCount,proto3" json:"series_count,omitempty"`
	HasUpdates    bool                   `protobuf:"varint,3,opt,name=has_updates,json=hasUpdates,proto3" json:"has_updates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckForUpdatesResponse) Reset() {
	*x = CheckForUpdatesResponse{}
	mi := &file_supersubtitles_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckForUpdatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckForUpdatesResponse) ProtoMessage() {}

func (x *CheckForUpdatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_supersubtitles_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckForUpdatesResponse.ProtoReflect.Descriptor instead.
func (*CheckForUpdatesResponse) Descriptor() ([]byte, []int) {
	return file_supersubtitles_proto_rawDescGZIP(), []int{9}
}

func (x *CheckForUpdatesResponse) GetFilmCount() int32 {
	if x != nil {
		return x.FilmCount
	}
	return 0
}

func (x *CheckForUpdatesResponse) GetSeriesCount() int32 {
	if x != nil {
		return x.SeriesCount
	}
	return 0
}

func (x *CheckForUpdatesResponse) GetHasUpdates() bool {
	if x != nil {
		return x.HasUpdates
	}
	return false
}

// DownloadSubtitleRequest requests a subtitle download
type DownloadSubtitleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubtitleId    string                 `protobuf:"bytes,1,opt,name=subtitle_id,json=subtitleId,proto3" json:"subtitle_id,omitempty"`
	Episode       *int32                 `protobuf:"varint,2,opt,name=episode,proto3,oneof" json:"episode,omitempty"` // Episode number to extract from season pack (not set = download entire file)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadSubtitleRequest) Reset() {
	*x = DownloadSubtitleRequest{}
	mi := &file_supersubtitles_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadSubtitleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadSubtitleRequest) ProtoMessage() {}

func (x *DownloadSubtitleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_supersubtitles_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadSubtitleRequest.ProtoReflect.Descriptor instead.
func (*DownloadSubtitleRequest) Descriptor() ([]byte, []int) {
	return file_supersubtitles_proto_rawDescGZIP(), []int{10}
}

func (x *DownloadSubtitleRequest) GetSubtitleId() string {
	if x != nil {
		return x.SubtitleId
	}
	return ""
}

func (x *DownloadSubtitleRequest) GetEpisode() int32 {
	if x != nil && x.Episode != nil {
		return *x.Episode
	}
	return 0
}

// DownloadSubtitleResponse contains the downloaded subtitle data
type DownloadSubtitleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadSubtitleResponse) Reset() {
	*x = DownloadSubtitleResponse{}
	mi := &file_supersubtitles_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadSubtitleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadSubtitleResponse) ProtoMessage() {}

func (x *DownloadSubtitleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_supersubtitles_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadSubtitleResponse.ProtoReflect.Descriptor instead.
func (*DownloadSubtitleResponse) Descriptor() ([]byte, []int) {
	return file_supersubtitles_proto_rawDescGZIP(), []int{11}
}

func (x *DownloadSubtitleResponse) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *DownloadSubtitleResponse) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *DownloadSubtitleResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

// GetRecentSubtitlesRequest requests recently uploaded subtitles
type GetRecentSubtitlesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SinceId       int64                  `protobuf:"varint,1,opt,name=since_id,json=sinceId,proto3" json:"since_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecentSubtitlesRequest) Reset() {
	*x = GetRecentSubtitlesRequest{}
	mi := &file_supersubtitles_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecentSubtitlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecentSubtitlesRequest) ProtoMessage() {}

func (x *GetRecentSubtitlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_supersubtitles_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecentSubtitlesRequest.ProtoReflect.Descriptor instead.
func (*GetRecentSubtitlesRequest) Descriptor() ([]byte, []int) {
	return file_supersubtitles_proto_rawDescGZIP(), []int{12}
}

func (x *GetRecentSubtitlesRequest) GetSinceId() int64 {
	if x != nil {
		return x.SinceId
	}
	return 0
}

var File_supersubtitles_proto protoreflect.FileDescriptor

const file_supersubtitles_proto_rawDesc = "" +
	"\n" +
	"\x14supersubtitles.proto\x12\x11supersubtitles.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"[\n" +
	"\x04Show\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x03R\x02id\x12\x12\n" +
	"\x04year\x18\x03 \x01(\x05R\x04year\x12\x1b\n" +
	"\timage_url\x18\x04 \x01(\tR\bimageUrl\"z\n" +
	"\rThirdPartyIds\x12\x17\n" +
	"\aimdb_id\x18\x01 \x01(\tR\x06imdbId\x12\x17\n" +
	"\atvdb_id\x18\x02 \x01(\x03R\x06tvdbId\x12\x1c\n" +
	"\n" +
	"tv_maze_id\x18\x03 \x01(\x03R\btvMazeId\x12\x19\n" +
	"\btrakt_id\x18\x04 \x01(\x03R\atraktId\"\xeb\x03\n" +
	"\bSubtitle\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\ashow_id\x18\x02 \x01(\x03R\x06showId\x12\x1b\n" +
	"\tshow_name\x18\x03 \x01(\tR\bshowName\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1a\n" +
	"\blanguage\x18\x05 \x01(\tR\blanguage\x12\x16\n" +
	"\x06season\x18\x06 \x01(\x05R\x06season\x12\x18\n" +
	"\aepisode\x18\a \x01(\x05R\aepisode\x12\x1a\n" +
	"\bfilename\x18\b \x01(\tR\bfilename\x12!\n" +
	"\fdownload_url\x18\t \x01(\tR\vdownloadUrl\x12\x1a\n" +
	"\buploader\x18\n" +
	" \x01(\tR\buploader\x12;\n" +
	"\vuploaded_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"uploadedAt\x128\n" +
	"\tqualities\x18\f \x03(\x0e2\x1a.supersubtitles.v1.QualityR\tqualities\x12%\n" +
	"\x0erelease_groups\x18\r \x03(\tR\rreleaseGroups\x12\x18\n" +
	"\arelease\x18\x0e \x01(\tR\arelease\x12$\n" +
	"\x0eis_season_pack\x18\x0f \x01(\bR\fisSeasonPack\"\x81\x01\n" +
	"\bShowInfo\x12+\n" +
	"\x04show\x18\x01 \x01(\v2\x17.supersubtitles.v1.ShowR\x04show\x12H\n" +
	"\x0fthird_party_ids\x18\x02 \x01(\v2 .supersubtitles.v1.ThirdPartyIdsR\rthirdPartyIds\"\x91\x01\n" +
	"\x10ShowSubtitleItem\x12:\n" +
	"\tshow_info\x18\x01 \x01(\v2\x1b.supersubtitles.v1.ShowInfoH\x00R\bshowInfo\x129\n" +
	"\bsubtitle\x18\x02 \x01(\v2\x1b.supersubtitles.v1.SubtitleH\x00R\bsubtitleB\x06\n" +
	"\x04item\"\x14\n" +
	"\x12GetShowListRequest\".\n" +
	"\x13GetSubtitlesRequest\x12\x17\n" +
	"\ashow_id\x18\x01 \x01(\x03R\x06showId\"H\n" +
	"\x17GetShowSubtitlesRequest\x12-\n" +
	"\x05shows\x18\x01 \x03(\v2\x17.supersubtitles.v1.ShowR\x05shows\"7\n" +
	"\x16CheckForUpdatesRequest\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\tR\tcontentId\"|\n" +
	"\x17CheckForUpdatesResponse\x12\x1d\n" +
	"\n" +
	"film_count\x18\x01 \x01(\x05R\tfilmCount\x12!\n" +
	"\fseries_count\x18\x02 \x01(\x05R\vseriesCount\x12\x1f\n" +
	"\vhas_updates\x18\x03 \x01(\bR\n" +
	"hasUpdates\"e\n" +
	"\x17DownloadSubtitleRequest\x12\x1f\n" +
	"\vsubtitle_id\x18\x01 \x01(\tR\n" +
	"subtitleId\x12\x1d\n" +
	"\aepisode\x18\x02 \x01(\x05H\x00R\aepisode\x88\x01\x01B\n" +
	"\n" +
	"\b_episode\"s\n" +
	"\x18DownloadSubtitleResponse\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\"6\n" +
	"\x19GetRecentSubtitlesRequest\x12\x19\n" +
	"\bsince_id\x18\x01 \x01(\x03R\asinceId*~\n" +
	"\aQuality\x12\x17\n" +
	"\x13QUALITY_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fQUALITY_360P\x10\x01\x12\x10\n" +
	"\fQUALITY_480P\x10\x02\x12\x10\n" +
	"\fQUALITY_720P\x10\x03\x12\x11\n" +
	"\rQUALITY_1080P\x10\x04\x12\x11\n" +
	"\rQUALITY_2160P\x10\x052\xe8\x04\n" +
	"\x15SuperSubtitlesService\x12O\n" +
	"\vGetShowList\x12%.supersubtitles.v1.GetShowListRequest\x1a\x17.supersubtitles.v1.Show0\x01\x12U\n" +
	"\fGetSubtitles\x12&.supersubtitles.v1.GetSubtitlesRequest\x1a\x1b.supersubtitles.v1.Subtitle0\x01\x12e\n" +
	"\x10GetShowSubtitles\x12*.supersubtitles.v1.GetShowSubtitlesRequest\x1a#.supersubtitles.v1.ShowSubtitleItem0\x01\x12h\n" +
	"\x0fCheckForUpdates\x12).supersubtitles.v1.CheckForUpdatesRequest\x1a*.supersubtitles.v1.CheckForUpdatesResponse\x12k\n" +
	"\x10DownloadSubtitle\x12*.supersubtitles.v1.DownloadSubtitleRequest\x1a+.supersubtitles.v1.DownloadSubtitleResponse\x12i\n" +
	"\x12GetRecentSubtitles\x12,.supersubtitles.v1.GetRecentSubtitlesRequest\x1a#.supersubtitles.v1.ShowSubtitleItem0\x01B5Z3github.com/Belphemur/SuperSubtitles/api/proto/v1;v1b\x06proto3"

var (
	file_supersubtitles_proto_rawDescOnce sync.Once
	file_supersubtitles_proto_rawDescData []byte
)

func file_supersubtitles_proto_rawDescGZIP() []byte {
	file_supersubtitles_proto_rawDescOnce.Do(func() {
		file_supersubtitles_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_supersubtitles_proto_rawDesc), len(file_supersubtitles_proto_rawDesc)))
	})
	return file_supersubtitles_proto_rawDescData
}

var file_supersubtitles_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_supersubtitles_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_supersubtitles_proto_goTypes = []any{
	(Quality)(0),                      // 0: supersubtitles.v1.Quality
	(*Show)(nil),                      // 1: supersubtitles.v1.Show
	(*ThirdPartyIds)(nil),             // 2: supersubtitles.v1.ThirdPartyIds
	(*Subtitle)(nil),                  // 3: supersubtitles.v1.Subtitle
	(*ShowInfo)(nil),                  // 4: supersubtitles.v1.ShowInfo
	(*ShowSubtitleItem)(nil),          // 5: supersubtitles.v1.ShowSubtitleItem
	(*GetShowListRequest)(nil),        // 6: supersubtitles.v1.GetShowListRequest
	(*GetSubtitlesRequest)(nil),       // 7: supersubtitles.v1.GetSubtitlesRequest
	(*GetShowSubtitlesRequest)(nil),   // 8: supersubtitles.v1.GetShowSubtitlesRequest
	(*CheckForUpdatesRequest)(nil),    // 9: supersubtitles.v1.CheckForUpdatesRequest
	(*CheckForUpdatesResponse)(nil),   // 10: supersubtitles.v1.CheckForUpdatesResponse
	(*DownloadSubtitleRequest)(nil),   // 11: supersubtitles.v1.DownloadSubtitleRequest
	(*DownloadSubtitleResponse)(nil),  // 12: supersubtitles.v1.DownloadSubtitleResponse
	(*GetRecentSubtitlesRequest)(nil), // 13: supersubtitles.v1.GetRecentSubtitlesRequest
	(*timestamppb.Timestamp)(nil),     // 14: google.protobuf.Timestamp
}
var file_supersubtitles_proto_depIdxs = []int32{
	14, // 0: supersubtitles.v1.Subtitle.uploaded_at:type_name -> google.protobuf.Timestamp
	0,  // 1: supersubtitles.v1.Subtitle.qualities:type_name -> supersubtitles.v1.Quality
	1,  // 2: supersubtitles.v1.ShowInfo.show:type_name -> supersubtitles.v1.Show
	2,  // 3: supersubtitles.v1.ShowInfo.third_party_ids:type_name -> supersubtitles.v1.ThirdPartyIds
	4,  // 4: supersubtitles.v1.ShowSubtitleItem.show_info:type_name -> supersubtitles.v1.ShowInfo
	3,  // 5: supersubtitles.v1.ShowSubtitleItem.subtitle:type_name -> supersubtitles.v1.Subtitle
	1,  // 6: supersubtitles.v1.GetShowSubtitlesRequest.shows:type_name -> supersubtitles.v1.Show
	6,  // 7: supersubtitles.v1.SuperSubtitlesService.GetShowList:input_type -> supersubtitles.v1.GetShowListRequest
	7,  // 8: supersubtitles.v1.SuperSubtitlesService.GetSubtitles:input_type -> supersubtitles.v1.GetSubtitlesRequest
	8,  // 9: supersubtitles.v1.SuperSubtitlesService.GetShowSubtitles:input_type -> supersubtitles.v1.GetShowSubtitlesRequest
	9,  // 10: supersubtitles.v1.SuperSubtitlesService.CheckForUpdates:input_type -> supersubtitles.v1.CheckForUpdatesRequest
	11, // 11: supersubtitles.v1.SuperSubtitlesService.DownloadSubtitle:input_type -> supersubtitles.v1.DownloadSubtitleRequest
	13, // 12: supersubtitles.v1.SuperSubtitlesService.GetRecentSubtitles:input_type -> supersubtitles.v1.GetRecentSubtitlesRequest
	1,  // 13: supersubtitles.v1.SuperSubtitlesService.GetShowList:output_type -> supersubtitles.v1.Show
	3,  // 14: supersubtitles.v1.SuperSubtitlesService.GetSubtitles:output_type -> supersubtitles.v1.Subtitle
	5,  // 15: supersubtitles.v1.SuperSubtitlesService.GetShowSubtitles:output_type -> supersubtitles.v1.ShowSubtitleItem
	10, // 16: supersubtitles.v1.SuperSubtitlesService.CheckForUpdates:output_type -> supersubtitles.v1.CheckForUpdatesResponse
	12, // 17: supersubtitles.v1.SuperSubtitlesService.DownloadSubtitle:output_type -> supersubtitles.v1.DownloadSubtitleResponse
	5,  // 18: supersubtitles.v1.SuperSubtitlesService.GetRecentSubtitles:output_type -> supersubtitles.v1.ShowSubtitleItem
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_supersubtitles_proto_init() }
func file_supersubtitles_proto_init() {
	if File_supersubtitles_proto != nil {
		return
	}
	file_supersubtitles_proto_msgTypes[4].OneofWrappers = []any{
		(*ShowSubtitleItem_ShowInfo)(nil),
		(*ShowSubtitleItem_Subtitle)(nil),
	}
	file_supersubtitles_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_supersubtitles_proto_rawDesc), len(file_supersubtitles_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_supersubtitles_proto_goTypes,
		DependencyIndexes: file_supersubtitles_proto_depIdxs,
		EnumInfos:         file_supersubtitles_proto_enumTypes,
		MessageInfos:      file_supersubtitles_proto_msgTypes,
	}.Build()
	File_supersubtitles_proto = out.File
	file_supersubtitles_proto_goTypes = nil
	file_supersubtitles_proto_depIdxs = nil
}
